# ─────────── aria2 ───────────
max-concurrent-downloads=16
continue=true
max-connection-per-server=16
min-split-size=1M
split=16
max-tries=5
retry-wait=3
connect-timeout=10
timeout=600
lowest-speed-limit=100K
summary-interval=0
piece-length=1M
disk-cache=128M
file-allocation=falloc
no-file-allocation-limit=8M
auto-file-renaming=false
allow-overwrite=true
remote-time=true
always-resume=true
http-accept-gzip=true
optimize-concurrent-downloads=true
user-agent=Transmission/2.77
peer-id-prefix=-TR2770-
peer-agent=Transmission/2.77
bt-max-peers=100
bt-request-peer-speed-limit=30M
seed-ratio=0.1
seed-time=0
listen-port=50101-50109
enable-dht=true
dht-listen-port=50101-50109
enable-dht6=true
bt-enable-lpd=true
follow-torrent=true
bt-detach-seed-only=true
dir=Videos
